/* Laundry Color Scanner service worker (blueprint §15).
 *
 * - One cache per build version; install fails (and the old worker stays)
 *   unless every precached file is fetched and verified.
 * - Cache-first for precached same-origin GETs; navigations inside the scope
 *   get the cached app shell, so HTML, JS, palette, config and worker always
 *   come from the same atomic version.
 * - Never intercepts cross-origin or non-GET requests; never caches images,
 *   uploads or AI responses.
 * - Activation of an update waits for the user ("Reload to update" on Home).
 */

// <precache> generated by scripts/build.mjs — do not edit by hand
const PRECACHE = {
  version: 'dee55b58dc0b',
  files: [
    './',
    'assets/icons/apple-touch-icon.png',
    'assets/icons/icon-192.png',
    'assets/icons/icon-512.png',
    'assets/icons/maskable-512.png',
    'data/colors.json',
    'data/detector-config.json',
    'data/reference-profiles.json',
    'index.html',
    'manifest.webmanifest',
    'src/ai/client.js',
    'src/ai/provider-contract.js',
    'src/app-config.js',
    'src/app.js',
    'src/camera.js',
    'src/color/cluster.js',
    'src/color/delta-e-2000.js',
    'src/color/match.js',
    'src/color/srgb-lab.js',
    'src/data-transfer.js',
    'src/detection/calibration.js',
    'src/detection/confidence.js',
    'src/detection/pattern.js',
    'src/detection/pipeline.js',
    'src/detection/quality.js',
    'src/detection/sampling.js',
    'src/detector-client.js',
    'src/geometry.js',
    'src/grouping.js',
    'src/image-input.js',
    'src/live-feedback.js',
    'src/pwa.js',
    'src/references.js',
    'src/schema.js',
    'src/storage.js',
    'src/ui/ai-review.js',
    'src/ui/camera-screen.js',
    'src/ui/color-picker.js',
    'src/ui/correction-screen.js',
    'src/ui/crop-screen.js',
    'src/ui/debug-view.js',
    'src/ui/dom.js',
    'src/ui/format.js',
    'src/ui/home-screen.js',
    'src/ui/messages.js',
    'src/ui/reference-screen.js',
    'src/ui/region-editor.js',
    'src/ui/results-screen.js',
    'src/ui/settings-screen.js',
    'src/util/hash.js',
    'src/util/ids.js',
    'src/worker/detector.worker.js',
    'styles/app.css',
  ],
};
// </precache>

const CACHE_PREFIX = 'laundry-color-scanner-';
const CACHE_NAME = `${CACHE_PREFIX}${PRECACHE.version}`;
const scopeUrl = new URL(self.registration.scope);
const PRECACHE_PATHS = new Set(PRECACHE.files.map((f) => new URL(f, scopeUrl).pathname));

async function verifyCache() {
  const cache = await caches.open(CACHE_NAME);
  const missing = [];
  for (const file of PRECACHE.files) {
    const response = await cache.match(new URL(file, scopeUrl));
    if (!response || !response.ok) missing.push(file);
  }
  return { ok: missing.length === 0, version: PRECACHE.version, missing };
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      // addAll is atomic: any failed file rejects install and keeps the old worker.
      await cache.addAll(PRECACHE.files.map((f) => new Request(new URL(f, scopeUrl), { cache: 'reload' })));
      const check = await verifyCache();
      if (!check.ok) throw new Error(`Precache incomplete: ${check.missing.join(', ')}`);
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k.startsWith(CACHE_PREFIX) && k !== CACHE_NAME).map((k) => caches.delete(k)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('message', (event) => {
  const type = event.data?.type;
  if (type === 'SKIP_WAITING') self.skipWaiting();
  else if (type === 'VERIFY_CACHE') {
    event.waitUntil(
      verifyCache()
        .catch(() => ({ ok: false, version: PRECACHE.version, missing: ['*'] }))
        .then((result) => event.ports[0]?.postMessage(result)),
    );
  }
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== scopeUrl.origin || !url.pathname.startsWith(scopeUrl.pathname)) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE_NAME);
        return (await cache.match(new URL('./', scopeUrl))) ?? (await cache.match(new URL('index.html', scopeUrl))) ?? fetch(request);
      })(),
    );
    return;
  }

  if (!PRECACHE_PATHS.has(url.pathname)) return;
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      // Match on origin + path so cache-busting query strings can't bypass the atomic version.
      return (await cache.match(url.origin + url.pathname)) ?? fetch(request);
    })(),
  );
});
