import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/**
 * Everything the offline app needs, relative to the deployment base.
 * Tests, scripts, docs and spec are development-only and never precached.
 */
const ROOT_FILES = ['index.html', 'manifest.webmanifest'];
const DIRS = ['styles', 'src', 'data', 'assets/icons'];
const EXTENSIONS = new Set(['.html', '.css', '.js', '.json', '.webmanifest', '.png', '.svg']);

const BLOCK_START = '// <precache> generated by scripts/build.mjs — do not edit by hand';
const BLOCK_END = '// </precache>';

export function listPrecacheFiles(root) {
  const files = ROOT_FILES.filter((f) => existsSync(join(root, f)));
  for (const dir of DIRS) {
    const abs = join(root, dir);
    if (existsSync(abs)) walk(abs, root, files);
  }
  return files.sort();
}

function walk(dir, root, out) {
  for (const name of readdirSync(dir).sort()) {
    const abs = join(dir, name);
    if (statSync(abs).isDirectory()) walk(abs, root, out);
    else if (EXTENSIONS.has(name.slice(name.lastIndexOf('.')))) out.push(relative(root, abs).split(sep).join('/'));
  }
}

/** Content hash over every precached path and its bytes (order-stable). */
export function computeBuildVersion(root, files) {
  const hash = createHash('sha256');
  for (const f of files) {
    hash.update(f);
    hash.update('\0');
    hash.update(readFileSync(join(root, f)));
    hash.update('\0');
  }
  return hash.digest('hex').slice(0, 12);
}

export function renderPrecacheBlock(version, files) {
  const list = ['./', ...files].map((f) => `    '${f}',`).join('\n');
  return `${BLOCK_START}\nconst PRECACHE = {\n  version: '${version}',\n  files: [\n${list}\n  ],\n};\n${BLOCK_END}`;
}

export function updatePrecache(root, { check = false } = {}) {
  const swPath = join(root, 'sw.js');
  if (!existsSync(swPath)) return { name: 'sw.js', changed: false, detail: 'no service worker yet' };
  const sw = readFileSync(swPath, 'utf8');
  const start = sw.indexOf(BLOCK_START);
  const end = sw.indexOf(BLOCK_END);
  if (start < 0 || end < start) throw new Error('sw.js is missing the <precache> block markers');
  const files = listPrecacheFiles(root);
  const version = computeBuildVersion(root, files);
  const next = sw.slice(0, start) + renderPrecacheBlock(version, files) + sw.slice(end + BLOCK_END.length);
  const changed = next !== sw;
  if (changed && !check) writeFileSync(swPath, next);
  return { name: 'sw.js', changed, detail: `build ${version}, ${files.length + 1} entries` };
}
